---
- hosts: "{{ variable_host | default('webservers') }}"
  vars_files:
    - vars.yaml
  become: yes
  become_method: sudo
  remote_user: '{{ user }}'

  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day 

  - name: install dependencies 
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - openjdk-11-jdk
      - apache2

  - name: enabled proxy mods
    apache2_module:
      name: "{{ item }}"
      state: present
    loop:
      - proxy
      - proxy_http

  - name: add tomcat group
    group:
      name: tomcat

  - name: add tomcat user
    user:
      name: tomcat
      group: tomcat
      home: /usr/share/tomcat
      createhome: no

  - name: create /opt/tomcat directory
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755
      owner: tomcat
      group: tomcat      
      recurse: yes
  
  - name: download & unarchive
    unarchive:
      src: '{{ tomcat_url }}'
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: update /opt/tomcat directory permissions
    file:
      path: /opt/tomcat
      mode: 0755
      owner: tomcat
      group: tomcat      
      recurse: yes


  - name: Copy Tomcat service from local to remote
    copy:
       src: tomcat.service
       dest: /etc/systemd/system/
       mode: 0755

  - name: Start and enable Tomcat service
    systemd:
      name: tomcat
      state: started
      enabled: true
      daemon_reload: true

  - name: Update apache config
    lineinfile:
      path: /etc/apache2/sites-enabled/000-default.conf
      line: '    ProxyPreserveHost On'
      insertbefore: '</VirtualHost>'
      

  - name: Update apache config2
    lineinfile:
      path: /etc/apache2/sites-enabled/000-default.conf
      line: '    ProxyPass / http://localhost:8080/'
      insertafter: '    ProxyPreserveHost On'
      
  - name: Restart apache2 service
    systemd:
      name: apache2
      state: restarted
      enabled: true
      daemon_reload: true
